# Generated by Django 6.1.1 on 2026-09-16 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('DUPLICATE_INVOICE', 'Duplicate Invoice Detected'), ('UNUSUAL_AMOUNT', 'Unusual Spending Spike / Outlier'), ('TAX_MISMATCH', 'Tax Calculation Discrepancy'), ('VENDOR_DISCREPANCY', 'Unrecognized Vendor Account'), ('LATE_PAYMENT_RISK', 'Immediate Late Payment Risk')], max_length=30)),
                ('severity', models.CharField(choices=[('HIGH', 'High Severity'), ('MEDIUM', 'Medium Severity'), ('LOW', 'Low Severity')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open Alert'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
