# Generated by Django 6.1.1 on 2026-09-16 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('UPLOAD_DOCUMENT', 'Uploaded Document'), ('EDIT_DOCUMENT', 'Edited Document Metadata'), ('DELETE_DOCUMENT', 'Deleted Document'), ('EXPORT_DATA', 'Exported Financial Ledger'), ('SEARCH_QUERY', 'Performed Semantic Search'), ('RESOLVE_ANOMALY', 'Resolved Anomaly Alert'), ('INVITE_MEMBER', 'Invited Team Member'), ('UPDATE_ROLE', 'Updated User Permissions'), ('UPDATE_PLAN', 'Upgraded Subscription Tier'), ('DOCUMENT_PROCESSED', 'AI Pipeline Completed')], max_length=40)),
                ('document_name', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
